CLASS LHC_ZR_TEST_GITABAP DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZrTestGitabap
        RESULT result,
      usernameBlank FOR VALIDATE ON SAVE
            IMPORTING keys FOR ZrTestGitabap~usernameBlank.
ENDCLASS.

CLASS LHC_ZR_TEST_GITABAP IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
  METHOD usernameBlank.
  ENDMETHOD.

ENDCLASS.
